name: Push
on: pull_request

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action step
        id: hello
        uses: ./.github/actions/chromatic
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Job output
        run: echo "${{ steps.hello.outputs.job_output }}"

      - name: PR number
        run: |
          echo "${{ github.event.number }}"

      - name: Configure gh cli
        run: |
          mkdir -p ~/.config/gh;
          echo "${{ secrets.GITHUB_TOKEN }}" >> mytoken.txt;
          gh auth login --with-token < mytoken.txt;

      - name: Write comment
        run: |
          gh pr comment ${{ github.event.number }} -b ${{ steps.hello.outputs.job_output }}
