name: Push
on: pull_request

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action step
        id: hello
        uses: ./.github/actions/chromatic

      - name: Job output
        run: echo "${{ steps.hello.outputs.job_output }}"

      - name: PR number
        run: |
          echo "${{ github.event.number }}"
